Add support for Symfony 6
paratestphp/paratest pull request #639
Opened 2021-11-05 10:07 UTC by loic425

2021-11-05 16:11 UTC, Slamdunk requested changes

2021-11-05 16:11 UTC, Slamdunk commented on .github/workflows/integrate.yaml
> +          - "6.0.*"
Hi, thank you for your PR.
I've pushed to your branch the removal of `vimeo/psalm` from tests build so circular reference gets out of the way.
It seems you are experienced with GA workflows: could you try to write a matrix where Symfony 6 is installed only on PHP versions it supports please?

2021-11-30 16:18 UTC, merged

2021-11-30 16:18 UTC, Slamdunk commented
Thank you @loic425

2021-11-30 16:23 UTC, loic425 commented
@Slamdunk I see you finish this one. Sorry I was not blocked anymore by this package cause Phpstan has merged the Symfony 6 support. But thank you for this support here too.