Update PhpstormHelper.php
paratestphp/paratest pull request #689
Opened 2022-08-22 17:01 UTC by alexndlm

In some environments, PHPUnit is located under `bin/phpunit`.

2022-08-22 19:38 UTC, Slamdunk requested changes
Please add a new data set in the related test so we ensure the feature you're requesting will never fade out

2022-08-24 17:26 UTC, alexndlm commented
Have done.

2022-08-25 05:34 UTC, Slamdunk requested changes

2022-08-25 05:34 UTC, Slamdunk commented on src/Util/PhpstormHelper.php
> +        $phpunitKey = self::getArgvKeyFor($argv, 'phpunit');
```suggestion
        $phpunitKey = self::getArgvKeyFor($argv, '/phpunit');
```

2022-08-25 05:43 UTC, Slamdunk approved these changes

2022-08-25 05:44 UTC, merged