Update to use PHP 8.4
paratestphp/paratest pull request #872
Opened 2024-08-12 11:23 UTC by joanhey

The tests pass, but show deprecations with the symfony/string class in lowest test.

Symfony/string is fixed https://github.com/symfony/string/commit/bce75043af265dc8aca536a6ab1d6b3181763529 

PD: perhaps it'll be better to change in `composer.json` :
```
"require": {
        "php": "~8.2.0 || ~8.3.0 || ~8.4.0",
```
with
```
"require": {
        "php": ">=8.2",
```

2024-08-20 14:21 UTC, Jean85 requested changes

2024-08-20 14:21 UTC, Jean85 commented on composer.json
> +        "php": ">=8.2",
Please do not put an open ended constraint here, the limited support to new PHP versions is intentional

2024-08-21 10:10 UTC, Slamdunk commented
I don't like the CI build on 8.4 to be successful: https://github.com/paratestphp/paratest/actions/runs/10473712966/job/29006479710?pr=872#step:3:19

`pcov` is not yet compatible with 8.4, https://github.com/krakjoe/pcov/pull/111

2024-09-25 08:24 UTC, Slamdunk commented
Apparently there's an infinite loop somewhere with PHP 8.4, but I can't debug it yet locally because the pcov PECL extension hasn't been updated yet, we need to wait

2024-10-15 12:38 UTC, Slamdunk commented
Superseded by https://github.com/paratestphp/paratest/pull/898 thank you anyway for your contribution

2024-10-15 12:38 UTC, closed without merging